apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: user-mgmt
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "mysecretpassword"
  POSTGRES_PASSWORD: "mysecretpassword"
  JWT_SECRET: "wIDAQABAkAzGlFARFau7K0b9FcEwIDAQABAkAzGlFARFau7K0b9FcEwIDAQABAkAzGlFARFau7K0b9FcE"