apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: user-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sidardenli/user-mgmt-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: user-mgmt
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080