apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: user-mgmt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: sidardenli/auth_portal:latest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: user-mgmt
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000